// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: internal/optim/preoptim/rpcServer/rpc.proto

package rpcserver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message for SayHello.
type AddCameraReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CameraId      string                 `protobuf:"bytes,1,opt,name=cameraId" json:"cameraId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCameraReq) Reset() {
	*x = AddCameraReq{}
	mi := &file_internal_optim_preoptim_rpcServer_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCameraReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCameraReq) ProtoMessage() {}

func (x *AddCameraReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_optim_preoptim_rpcServer_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCameraReq.ProtoReflect.Descriptor instead.
func (*AddCameraReq) Descriptor() ([]byte, []int) {
	return file_internal_optim_preoptim_rpcServer_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *AddCameraReq) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

// The response message for SayHello.
type AddCameraResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCameraResp) Reset() {
	*x = AddCameraResp{}
	mi := &file_internal_optim_preoptim_rpcServer_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCameraResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCameraResp) ProtoMessage() {}

func (x *AddCameraResp) ProtoReflect() protoreflect.Message {
	mi := &file_internal_optim_preoptim_rpcServer_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCameraResp.ProtoReflect.Descriptor instead.
func (*AddCameraResp) Descriptor() ([]byte, []int) {
	return file_internal_optim_preoptim_rpcServer_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *AddCameraResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_internal_optim_preoptim_rpcServer_rpc_proto protoreflect.FileDescriptor

const file_internal_optim_preoptim_rpcServer_rpc_proto_rawDesc = "" +
	"\n" +
	"+internal/optim/preoptim/rpcServer/rpc.proto\x12\trpcserver\"*\n" +
	"\fAddCameraReq\x12\x1a\n" +
	"\bcameraId\x18\x01 \x01(\tR\bcameraId\")\n" +
	"\rAddCameraResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2Q\n" +
	"\x0fPreOptimService\x12>\n" +
	"\tAddCamera\x12\x17.rpcserver.AddCameraReq\x1a\x18.rpcserver.AddCameraRespB\x12Z\v./rpcserver\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var (
	file_internal_optim_preoptim_rpcServer_rpc_proto_rawDescOnce sync.Once
	file_internal_optim_preoptim_rpcServer_rpc_proto_rawDescData []byte
)

func file_internal_optim_preoptim_rpcServer_rpc_proto_rawDescGZIP() []byte {
	file_internal_optim_preoptim_rpcServer_rpc_proto_rawDescOnce.Do(func() {
		file_internal_optim_preoptim_rpcServer_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_optim_preoptim_rpcServer_rpc_proto_rawDesc), len(file_internal_optim_preoptim_rpcServer_rpc_proto_rawDesc)))
	})
	return file_internal_optim_preoptim_rpcServer_rpc_proto_rawDescData
}

var file_internal_optim_preoptim_rpcServer_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_optim_preoptim_rpcServer_rpc_proto_goTypes = []any{
	(*AddCameraReq)(nil),  // 0: rpcserver.AddCameraReq
	(*AddCameraResp)(nil), // 1: rpcserver.AddCameraResp
}
var file_internal_optim_preoptim_rpcServer_rpc_proto_depIdxs = []int32{
	0, // 0: rpcserver.PreOptimService.AddCamera:input_type -> rpcserver.AddCameraReq
	1, // 1: rpcserver.PreOptimService.AddCamera:output_type -> rpcserver.AddCameraResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_optim_preoptim_rpcServer_rpc_proto_init() }
func file_internal_optim_preoptim_rpcServer_rpc_proto_init() {
	if File_internal_optim_preoptim_rpcServer_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_optim_preoptim_rpcServer_rpc_proto_rawDesc), len(file_internal_optim_preoptim_rpcServer_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_optim_preoptim_rpcServer_rpc_proto_goTypes,
		DependencyIndexes: file_internal_optim_preoptim_rpcServer_rpc_proto_depIdxs,
		MessageInfos:      file_internal_optim_preoptim_rpcServer_rpc_proto_msgTypes,
	}.Build()
	File_internal_optim_preoptim_rpcServer_rpc_proto = out.File
	file_internal_optim_preoptim_rpcServer_rpc_proto_goTypes = nil
	file_internal_optim_preoptim_rpcServer_rpc_proto_depIdxs = nil
}
