// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Camera struct {
	CameraID   int64
	JunctionID int64
	RtspUrl    string
	Angle      float64
	Resolution string
	Status     interface{}
	CreatedAt  pgtype.Timestamptz
	PolicyID   int64
}

type Junction struct {
	JunctionID int64
	Name       string
	Latitude   float64
	Longitude  float64
	Status     interface{}
	CreatedAt  pgtype.Timestamptz
	City       pgtype.Text
}

type Policy struct {
	PolicyID int64
	GreenMin int32
	GreenMax int32
	RedMin   int32
	RedMax   int32
	CycleMax int32
}
