// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAllCameras = `-- name: GetAllCameras :many
SELECT
    cameras.camera_id,
    cameras.junction_id,
    cameras.rtsp_url,
    cameras.angle,
    cameras.resolution,
    cameras.status::TEXT AS status,
    cameras.created_at,
    junctions.name AS juncName,
    junctions.latitude,
    junctions.longitude
FROM cameras
JOIN junctions ON junctions.junction_id = cameras.junction_id
`

type GetAllCamerasRow struct {
	CameraID   int64
	JunctionID int64
	RtspUrl    string
	Angle      float64
	Resolution string
	Status     string
	CreatedAt  pgtype.Timestamptz
	Juncname   string
	Latitude   float64
	Longitude  float64
}

func (q *Queries) GetAllCameras(ctx context.Context) ([]GetAllCamerasRow, error) {
	rows, err := q.db.Query(ctx, getAllCameras)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllCamerasRow
	for rows.Next() {
		var i GetAllCamerasRow
		if err := rows.Scan(
			&i.CameraID,
			&i.JunctionID,
			&i.RtspUrl,
			&i.Angle,
			&i.Resolution,
			&i.Status,
			&i.CreatedAt,
			&i.Juncname,
			&i.Latitude,
			&i.Longitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCameraInfo = `-- name: GetCameraInfo :one
SELECT
    cameras.camera_id,
    cameras.junction_id,
    cameras.rtsp_url,
    cameras.angle,
    cameras.resolution,
    cameras.status::TEXT AS status,
    cameras.created_at,
    junctions.name AS juncName,
    junctions.latitude,
    junctions.longitude
FROM cameras
JOIN junctions ON junctions.junction_id = cameras.junction_id
WHERE cameras.camera_id = $1
`

type GetCameraInfoRow struct {
	CameraID   int64
	JunctionID int64
	RtspUrl    string
	Angle      float64
	Resolution string
	Status     string
	CreatedAt  pgtype.Timestamptz
	Juncname   string
	Latitude   float64
	Longitude  float64
}

func (q *Queries) GetCameraInfo(ctx context.Context, cameraID int64) (GetCameraInfoRow, error) {
	row := q.db.QueryRow(ctx, getCameraInfo, cameraID)
	var i GetCameraInfoRow
	err := row.Scan(
		&i.CameraID,
		&i.JunctionID,
		&i.RtspUrl,
		&i.Angle,
		&i.Resolution,
		&i.Status,
		&i.CreatedAt,
		&i.Juncname,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const getPoliciesForCameraID = `-- name: GetPoliciesForCameraID :one
WITH temp AS (
    SELECT
        cameras.policy_id
    FROM cameras
    WHERE cameras.camera_id = $1
)

SELECT
    policies.policy_id,
    policies.green_min,
    policies.green_max,
    policies.red_min,
    policies.red_max,
    policies.cycle_max
FROM policies
WHERE policies.policy_id = temp.policy_id
`

func (q *Queries) GetPoliciesForCameraID(ctx context.Context, cameraID int64) (Policy, error) {
	row := q.db.QueryRow(ctx, getPoliciesForCameraID, cameraID)
	var i Policy
	err := row.Scan(
		&i.PolicyID,
		&i.GreenMin,
		&i.GreenMax,
		&i.RedMin,
		&i.RedMax,
		&i.CycleMax,
	)
	return i, err
}
